apiVersion: batch/v1
kind: Job
metadata:
  name: restart-payment-rollout
  namespace: otel-demo
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -lc
            - kubectl rollout restart deployment/paymentservice -n otel-demo
