apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: payment-unreachable
  namespace: chaos-testing
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - otel-demo
    labelSelectors:
      app.kubernetes.io/name: paymentservice
  direction: both
  target:
    mode: all
    selector:
      namespaces:
        - otel-demo
      labelSelectors:
        app.kubernetes.io/name: checkoutservice
